#!/usr/bin/bash
# This code write by Mr.nope
clear
echo "Updating..."
sleep 2
cd .. && cd .. && sudo rm -r Hack-Framework && git clone https://github.com/mrprogrammer2938/Hack-Framework && cd Hack-Framework && bash install.sh
echo ""
clear
echo "Updating Complate!"
echo ""
echo "usage: ./hack"
echo ""
exit 1
